import Head from 'next/head'

type Props ={
  title? : string
}

const SEO = ({title} : Props)=>(
  <Head>
    <title>Create Next App || {title} </title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
)

export default SEO;